version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tmh_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-tmh_super_secret_jwt_key_2026}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-kZ_3eP9sN0fQ7uL1jX8wV2bM5rT4yU6iO3pA7dE1gH0=}
      - DATABASE_URL=postgresql://tmh_user:tmh_pass@postgres:5432/tmh_db
      - ASYNC_DATABASE_URL=postgresql+asyncpg://tmh_user:tmh_pass@postgres:5432/tmh_db
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:-37975206}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-05c1d0668fb608e464154f3030b055af}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:8000/api/v1/drive/callback}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./temp_storage:/app/temp_storage

  postgres:
    image: postgres:16-alpine
    container_name: tmh_postgres
    restart: always
    environment:
      - POSTGRES_USER=tmh_user
      - POSTGRES_PASSWORD=tmh_pass
      - POSTGRES_DB=tmh_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tmh_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
